start = root 
root = element root {title, author, poem, info, metaData} 
title = element title {attribute mainTitle {text}, text} 
author = element author {attribute name {text}, text}
poem = element poem {attribute main {text}, (line | stamp)+ } 
line = element line {attribute num {xsd:integer}, mixed { (historicalFig | rhyme | lineBreak | location | emphasis)*}}
historicalFig = element historicalFig {attribute historicalName {text}, text}
stamp = element stamp {attribute alt {text}, text} 
rhyme = element rhyme {attribute with {text}, text} 
lineBreak = element lineBreak {attribute lineB {text}, text} 
location = element location {attribute where {text}, text} 
emphasis = element emphasis {attribute emphasize {text}, text} 
info = element info {author, finalDraft, sublocation, location, date} 
finalDraft = element finalDraft {text} 
sublocation = element sublocation {text} 
date = element date {attribute time {text}, text} 
metaData = element metaData {attribute info {text}, source} 
source = element source { mixed { (author | sourceLocation | historicalFig | sourceDate)*}} 
sourceLocation = element sourceLocation {text} 
sourceDate = element sourceDate {text} 
